name: Deploy Sphinx Documentation

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install sphinx sphinx-rtd-theme myst-parser

            - name: Sphinx build
              run: |
                  sphinx-build doc _build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: _build/
                  force_orphan: true
