name: Documentation Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install sphinx sphinx-rtd-theme
            - name: Build documentation
              run: |
                  cd docs
                  make html
